version: "3.6"
services:
  frontend:
    depends_on:
      - roboscan
    build: ../scanner-frontend/
    image: yatesdev/roboscan_scanner-frontend:2.1
    restart: unless-stopped
    ports:
      - 80:80
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /run # Note that there's a symbolic link /var/run -> /run
    volumes:
      - /home/pi/storage/share:/share:ro
      - /home/pi/storage/archive:/archive:ro
  roboscan:
    build: ../src/
    image: yatesdev/roboscan_scanner:2.1
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /home/pi/storage:/storage
      - /home/pi/configuration:/configuration
      - /dev/bus/usb/:/dev/bus/usb
    privileged: true
  rsyncd:
    build: ./rsyncd/
    image: yatesdev/roboscan_rsyncd:2.1
    ports:
      - "873:873"
    volumes:
      - /home/pi/storage/share:/share:ro
    read_only: true
    tmpfs:
      - /run # Note that there's a symbolic link /var/run -> /run
    restart: unless-stopped
  samba:
    image: dperson/samba
    environment:
      SHARE: "share;/share"
      SHARE1: "archive;/archive"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    volumes:
      - /home/pi/storage/share:/share
      - /home/pi/storage/archive:/archive
